apiVersion: v1
kind: Service
metadata:
  name: stratum-app
  namespace: stratum
  labels:
    app: stratum-app
spec:
  selector:
    app: stratum-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP